### ISSUE TITLE
Sign Release Mac Binary

### ISSUE THREAD

**Issue by swznd** [Electrum-RVN-SIG/electrum-ravencoin#15]
When launching a user receives the error

    “Electrum-Ravencoin” can’t be opened because it is from an unidentified developer.

There is a work around. However, best practice is to sign these binaries.

**Comment by kralverde** [comment]
Will look into this

**Comment by swznd** [comment]
please let me know if i can be of any help

**Comment by kralverde** [comment]
I think I'll wait until v1.0.0 (when I expect to add everything ravencoin related) before paying apple to verify these binaries. I'll also ask the ravencoin foundation about being able to use the same keys as the upcoming p2sh release (in which case I'll make a signed release sooner)

**Comment by kralverde** [comment]
Someone is graciously letting me use their Developer ID to sign these electrum binaries, so I should have a signed v0.4.4.1 sooner rather than later. Currently the app can be run from anywhere, however -- for whatever reason -- the app inside of the dmg is failing to be run on other machines because of an internal PyInstaller error (it can still be run from the DMG on the machine that built it, it's weird). Just wanted to give you an update.

**Comment by kralverde** [comment]
DMGs just don't work on other macs now, so this will have to wait

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v0.4.6
